apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-cognee
spec:
    type: {{ .Values.service.type }}
    selector:
        app: {{ .Release.Name }}-cognee
    ports:
        - port: {{ .Values.service.port }}
          targetPort: 8000
